version: '3'
services: 
  deploy:
    image: wendll/node_ansible_container:latest
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ~/.ssh:/ansible/.ssh
      - .:/ansible/playbooks
      - /ansible/playbooks/node_modules